import { LessonCreateInput } from '.keystone/types'

export const lessons = [
  {
    name: 'U10 Monday Test Lesson',
    time: '5:30pm',
    day: 'MONDAY',
    lengthMin: 60,
    maxYear: 10,
    minYear: 8,
    location: 'Test Location',
    lessonCategory: { connect: { slug: 'drama-club' } },
    cost: 1500,
  },
  {
    name: 'U10 Wednesday Test Lesson',
    time: '5:30pm',
    day: 'WEDNESDAY',
    lengthMin: 60,
    maxYear: 10,
    minYear: 8,
    location: 'Test Location',
    lessonCategory: { connect: { slug: 'drama-club' } },
    cost: 1500,
  },
  {
    name: 'U12 Monday Test Lesson',
    time: '6:30pm',
    day: 'MONDAY',
    lengthMin: 60,
    maxYear: 12,
    minYear: 10,
    location: 'Test Location',
    lessonCategory: { connect: { slug: 'drama-club' } },
    cost: 1500,
  },
  {
    name: 'U12 Wednesday Test Lesson',
    time: '6:30pm',
    day: 'WEDNESDAY',
    lengthMin: 60,
    maxYear: 12,
    minYear: 10,
    location: 'Test Location',
    lessonCategory: { connect: { slug: 'drama-club' } },
    cost: 1500,
  },
  {
    name: 'U14 Monday Test Lesson',
    time: '7:30pm',
    day: 'MONDAY',
    lengthMin: 60,
    maxYear: 14,
    minYear: 12,
    location: 'Test Location',
    lessonCategory: { connect: { slug: 'drama-teens' } },
    cost: 1500,
  },
  {
    name: 'U14 Wednesday Test Lesson',
    time: '7:30pm',
    day: 'WEDNESDAY',
    lengthMin: 60,
    maxYear: 14,
    minYear: 12,
    location: 'Test Location',
    lessonCategory: { connect: { slug: 'drama-teens' } },
    cost: 1500,
  },
  {
    name: 'U16 Monday Test Lesson',
    time: '8:30pm',
    day: 'MONDAY',
    lengthMin: 60,
    maxYear: 16,
    minYear: 14,
    location: 'Test Location',
    lessonCategory: { connect: { slug: 'advanced-actors' } },
    cost: 1500,
  },
  {
    name: 'U16 Wednesday Test Lesson',
    time: '8:30pm',
    day: 'WEDNESDAY',
    lengthMin: 60,
    maxYear: 16,
    minYear: 14,
    location: 'Test Location',
    lessonCategory: { connect: { slug: 'advanced-actors' } },
    cost: 1500,
  },
] satisfies LessonCreateInput[]
