/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/j21zSbLekUT
 */
import { AvatarImage, AvatarFallback, Avatar } from 'components/ui/avatar'
import { HoverCardTrigger, HoverCard } from 'components/ui/hover-card'

export function StaffBio() {
  // TODO: repalce with keystone data
  const staff = [
    {
      name: 'Olivia Smith',
      position: 'Violin',
      description: `Olivia is a passionate and dedicated violinist and performer, completing extensive AMEB 
      examinations, performing with the State School Spectacular orchestra, Bendigo Theatre company’s pit 
      orchestra and the Bendigo Symphonie Orchestra, Olivia has a wealth on ensemble and soloistic performance experience to endue.`,
      photo: '/placeholder.svg?height=200&width=200',
      fallback: 'OS',
    },
    {
      name: 'Breanna Henderson',
      position: 'Violin/ Viola/ early childhood music',
      description: `Breanna is a talented and dedicated musician and educator. With a particular interest in
      violin teaching and early childhood music education. Breanna has accomplished extensive
      AMEB exams in both violin and Viola, performing with ensembles, quartets, orchestras and
      choirs across Victoria.`,
      photo: '/staff-photos/staff_photo_breanna.png',
    },
    {
      name: 'Jasmine Brambly',
      position: 'Drama',
      description: `Jasmine has been part of the Drama club’s teacher training internship program for the past
      12 months and her most recent achievements include assistant director for the Drama clubs
      most recent production of Alice in wonderland and Wyrd sisters. Jasmine has been
      mastering her theatre and performance skills through the Academy of creative arts
      program, many theatrical performances and the completion for her 7 th grade AMEB Drama
      exam.`,
      photo: '/staff-photos/staff_photo_jasmine.png',
    },
    {
      name: 'Leah Grotto',
      position: 'Drama',
      description: `Leah has been part of the Drama club’s teacher training internship program for the past 12
      months and her most recent achievements include co choreographer and playing a major
      role in the Drama clubs most recent production of Alice in wonderland. Leah has performed
      in many productions with Tribe youth theatre, Uncertain curtain and On the hill theatre
      over the years. Leah has recently completed her 7 th grade AMEB Drama exam.`,
      photo: '/staff-photos/staff_photo_leah.png',
    },
    {
      name: 'Catherine Dorer',
      position: 'Drama',
      description: `Catherine (also known as Katya) has been part of the Drama club’s for the last 7 years, at
      the beginning of 3023 she began the teacher training internship program. Katya has brought
      a new creative and artistic element to the drama clubs productions in artistic elements,
      props and costume creation in the Drama clubs most recent production of Alice in
      wonderland and Wyrd sisters. Katya completion for her 7 th grade AMEB Drama exam,
      particularly exploring Greek theatre and literary texts.`,
      photo: '/staff-photos/staff_photo_catherine.png',
    },
    {
      name: 'Will Calder',
      position: 'Drama',
      description: `Will has been part of the Drama club’s teacher training internship program for the past 12
      months, his most recent achievements include stage manager, set designer/ creator for the
      Drama clubs most recent production of Alice in wonderland and Wyrd sister. Will has a long
      performance career with 20+ productions, 8 years of tuition and the completion for his 7 th
      grade AMEB Drama exam.`,
      photo: '/staff-photos/staff_photo_will.png',
    },
    {
      name: 'Elli Calder',
      position: 'Drama/Early Childhood Music',
      description: `For the last 12 months Elli has been part of the Drama club’s teacher training internship
      program, competing in competitions in NSW and Victoria. Elli recently completed her 6 th
      grade AMEB Drama exam. Her most recent achievements include co choreographer and
      playing a major role in the Drama clubs most recent production of Alice in wonderland.
      Performing in many productions with Tribe youth theatre, Bendigo Theatre company,
      Uncertain curtain and On the hill theatre.`,
      photo: '/staff-photos/staff_photo_elli.png',
    },
  ]
  return (
    <section className="flex flex-col items-center justify-center space-y-8 bg-[#ffffff] px-4 py-8 dark:bg-[#000000] md:space-y-16 md:px-6 md:py-12">
      <div className="space-y-2 text-center">
        <h2 className="text-3xl font-bold md:text-4xl">Our Teachers</h2>
        <p className="text-gray-500 dark:text-gray-400 md:text-lg">
          Meet our team of teachers who are passionate about what they do.
        </p>
      </div>
      <div className="flex flex-col items-center justify-center gap-8 md:gap-12">
        {staff.map(({ name, position, description, photo, fallback }) => (
          <HoverCard key={fallback}>
            <HoverCardTrigger asChild>
              <div className="flex flex-row items-center gap-4 md:gap-8">
                <Avatar className="h-36 w-24 md:h-40 md:w-32">
                  <AvatarImage alt={name} src={photo} />
                  <AvatarFallback>{fallback}</AvatarFallback>
                </Avatar>
                <div className="space-y-1">
                  <h4 className="text-lg font-semibold">{name}</h4>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    {position}
                  </p>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    {description}
                  </p>
                </div>
              </div>
            </HoverCardTrigger>
          </HoverCard>
        ))}
      </div>
    </section>
  )
}
