name: Test on PR

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@main
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm

      - run: pnpm install
      - run: pnpm lint
