name: Test on PR

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Latest Corepack
        run: |
          echo "Before: corepack version => $(corepack --version || echo 'not installed')"
          npm install -g corepack@latest
          echo "After : corepack version => $(corepack --version)"
          corepack enable
          pnpm --version

      - uses: actions/setup-node@main
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm

      - run: pnpm install
      - run: pnpm lint
